//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopusSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Verso", Namespace="http://schemas.datacontract.org/2004/07/Verso.Net.Commons")]
    [System.SerializableAttribute()]
    public partial class Verso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataVersoExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceBlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceTypeGeneric TypeVersoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataVersoExtension {
            get {
                return this.DataVersoExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DataVersoExtensionField, value) != true)) {
                    this.DataVersoExtensionField = value;
                    this.RaisePropertyChanged("DataVersoExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceBlock {
            get {
                return this.ServiceBlockField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceBlockField, value) != true)) {
                    this.ServiceBlockField = value;
                    this.RaisePropertyChanged("ServiceBlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OctopusSvc.ServiceTypeGeneric TypeVerso {
            get {
                return this.TypeVersoField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeVersoField, value) != true)) {
                    this.TypeVersoField = value;
                    this.RaisePropertyChanged("TypeVerso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Verb {
            get {
                return this.VerbField;
            }
            set {
                if ((object.ReferenceEquals(this.VerbField, value) != true)) {
                    this.VerbField = value;
                    this.RaisePropertyChanged("Verb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceTypeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Verso.Net.Commons")]
    [System.SerializableAttribute()]
    public partial class ServiceTypeGeneric : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssemblyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyName {
            get {
                return this.AssemblyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssemblyNameField, value) != true)) {
                    this.AssemblyNameField = value;
                    this.RaisePropertyChanged("AssemblyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OctopusSvc.IServiceBlock")]
    public interface IServiceBlock {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBlock/ExecuteServiceBlock", ReplyAction="http://tempuri.org/IServiceBlock/ExecuteServiceBlockResponse")]
        OctopusSvc.Verso ExecuteServiceBlock(OctopusSvc.Verso verso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBlockChannel : OctopusSvc.IServiceBlock, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBlockClient : System.ServiceModel.ClientBase<OctopusSvc.IServiceBlock>, OctopusSvc.IServiceBlock {
        
        public ServiceBlockClient() {
        }
        
        public ServiceBlockClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBlockClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBlockClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBlockClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OctopusSvc.Verso ExecuteServiceBlock(OctopusSvc.Verso verso) {
            return base.Channel.ExecuteServiceBlock(verso);
        }
    }
}
